# Generated by Django 3.2.4 on 2021-06-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0004_alter_componente_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='caracteristica',
            field=models.TextField(),
        ),
    ]
