# Generated by Django 3.2.4 on 2021-07-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0006_alter_componente_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='imagen',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
