# Generated by Django 3.2.4 on 2021-07-01 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0010_alter_carrito_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='cantidad',
            new_name='total',
        ),
        migrations.CreateModel(
            name='productoCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.PositiveIntegerField()),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCommerce.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCommerce.componente')),
            ],
        ),
    ]
