# Generated by Django 3.2.4 on 2021-07-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0011_auto_20210701_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
    ]
