# Generated by Django 3.2.4 on 2021-07-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0012_alter_componente_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocarrito',
            name='valor',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
