# Generated by Django 3.2.4 on 2021-07-01 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0013_productocarrito_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productocarrito',
            old_name='valor',
            new_name='precio',
        ),
    ]
