# Generated by Django 3.2.4 on 2021-07-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0014_rename_valor_productocarrito_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocarrito',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
    ]
